### PR TITLE
Multi file upload

### PR DESCRIPTION
**Pull request by mrloop**
## What Changed & Why
Support multiple file upload that are matched using filePattern.
Backwards compatible, default is old behavior using single index.html file.
Multiple files stored in redis hash using `HMSET`

## Related issues
#55 

## PR Checklist
- [x] Add tests
- [ ] Add documentation
- [ ] Prefix documentation-only commits with [DOC]

## People
@YoranBrondsema

### CODE REVIEW

**Comment by duizendnegen** [comment]
What's the use case exactly? In what situation do you want to upload multiple files this way?
Would it be possible for the multiple files to get a different key suffix instead? The concern is that users are caught by surprise by the different data structure on the old key they relied on.

**Comment by achambers** [comment]
@mrloop So I can get a better idea, what are the files that you want to upload? This redis plugin as was intended, and really only ever gets used to upload the `index.{html,json}` file. What is an example of the other files you want to upload?

Are you saying that you're trying to upload all your assets to redis and then your web server will pull the assets from there to serve them?

**Comment by YoranBrondsema** [comment]
@mrloop Have you considered including the plugin multiple times, i.e. once for each file you want to upload (see http://ember-cli-deploy.com/docs/v1.0.x/including-a-plugin-twice/)? That is the solution that I ended up using for the issue #55 that you referenced.

**Comment by mrloop** [comment]
I've reworked app / deploy and am now serving majority of assets directly from nginx. Serving 2 files from redis / app server `index.html` and `manifest.appcache`, managing the 2 files to be deployed via ember-cli-deploy-redis with aliases. 

Closing this PR, however if there is any value to it would be happy to work further on it.

**Pull request closed without merging**
