### PR TITLE
Remove unused maxRecentUploads from upload method

### PR DESCRIPTION
**Pull request by zzarcon**
Just a minor thing... thanks for the package!

### CODE REVIEW

**Comment by ghedamat** [comment]
@zzarcon this should be used indeed, it's passed with the other options to `lib/redis` here
https://github.com/ember-cli-deploy/ember-cli-deploy-redis/blob/master/index.js#L53

and then here https://github.com/ember-cli-deploy/ember-cli-deploy-redis/blob/master/lib/redis.js#L33

is that not working for you?

we might have a bug then

**Comment by ghedamat** [comment]
@zzarcon friendly ping

**Comment by zzarcon** [comment]
@ghedamat sorry for the delay, I think we can close the PR. The code was working fine for me, I just thought we could get rid of `this.readConfig('maxRecentUploads')` since we are not using it later on there ^^. Anyways was just a minor thing, thanks for the feedback!

**Comment by ghedamat** [comment]
No problem!

**Pull request closed without merging**
